const cardGenres = {
  fruits: [
    { id: 1, name: 'apple', imgUrl: 'fruits/apple.jpg' },
    { id: 2, name: 'banana', imgUrl: 'fruits/banana.png' },
    { id: 3, name: 'orange', imgUrl: 'fruits/orange.png' },
    { id: 4, name: 'peach', imgUrl: 'fruits/peach.jpg' },
    { id: 5, name: 'grapes', imgUrl: 'fruits/grapes.jpg' },
  ],
  sports: [
    { id: 1, name: 'football', imgUrl: 'sports/football.jpg' },
    { id: 2, name: 'basketball', imgUrl: 'sports/basketball.jpg' },
    { id: 3, name: 'tennis', imgUrl: 'sports/tennis.jpg' },
    { id: 4, name: 'baseball', imgUrl: 'sports/baseball.jpg' },
  ],
  vegetables: [
    { id: 1, name: 'carrot', imgUrl: 'vegetables/carrot.jpg' },
    { id: 2, name: 'broccoli', imgUrl: 'vegetables/broccoli.jpg' },
    { id: 3, name: 'tomato', imgUrl: 'vegetables/tomato.jpg' },
    { id: 4, name: 'potato', imgUrl: 'vegetables/potato.jpg' },
  ],
  小3の1_国: [
    { id: 1, name: 'Finland', imgUrl: '31/carrot.jpg' },
    { id: 2, name: 'China', imgUrl: '31/broccoli.jpg' },
    { id: 3, name: 'Japan', imgUrl: '31/tomato.jpg' },
    { id: 4, name: 'America', imgUrl: '31/potato.jpg' },
  ],
  小3の2_きもち: [
    { id: 1, name: 'happy', imgUrl: '32/happy.jpg' },
    { id: 2, name: 'sleepy', imgUrl: '32/happy.jpg' },
    { id: 3, name: 'hungry', imgUrl: '32/happy.jpg' },
    { id: 4, name: 'tired', imgUrl: '32/happy.jpg' },
    { id: 5, name: 'sad', imgUrl: '32/happy.jpg' },
  ],
  小3の3_かず: [
    { id: 1, name: '1', imgUrl: '32/happy.jpg' },
    { id: 2, name: '2', imgUrl: '32/happy.jpg' },
    { id: 3, name: '3', imgUrl: '32/happy.jpg' },
    { id: 4, name: '4', imgUrl: '32/happy.jpg' },
    { id: 5, name: '5', imgUrl: '32/happy.jpg' },
    { id: 6, name: '6', imgUrl: '32/happy.jpg' },
    { id: 7, name: '7', imgUrl: '32/happy.jpg' },
    { id: 8, name: '8', imgUrl: '32/happy.jpg' },
    { id: 9, name: '9', imgUrl: '32/happy.jpg' },
    { id: 10, name: '10', imgUrl: '32/happy.jpg' },
    { id: 11, name: '11', imgUrl: '32/happy.jpg' },
    { id: 12, name: '12', imgUrl: '32/happy.jpg' },
    { id: 13, name: '13', imgUrl: '32/happy.jpg' },
    { id: 14, name: '14', imgUrl: '32/happy.jpg' },
    { id: 15, name: '15', imgUrl: '32/happy.jpg' },
    { id: 16, name: '16', imgUrl: '32/happy.jpg' },
    { id: 17, name: '17', imgUrl: '32/happy.jpg' },
    { id: 18, name: '18', imgUrl: '32/happy.jpg' },
    { id: 19, name: '19', imgUrl: '32/happy.jpg' },
    { id: 20, name: '20', imgUrl: '32/happy.jpg' },
  ],
  小4の2_服_天気: [
    { id: 1, name: 'sunny', imgUrl: '/42/sunny.jpg' },
    { id: 2, name: 'rainy', imgUrl: '/42/rainy.jpg' },
    { id: 3, name: 'snowy', imgUrl: '/42/snowy.jpg' },
    { id: 4, name: 'cloudy', imgUrl: '/42/cloudy.jpg' },
    { id: 5, name: 'hot', imgUrl: '/42/hot.jpg' },
    { id: 6, name: 'cold', imgUrl: '/42/cold.jpg' },
    { id: 7, name: 'shorts', imgUrl: '/42/shorts.jpg' },
    { id: 8, name: 'shirt', imgUrl: '/42/shirt.jpg' },
    { id: 9, name: 'pants', imgUrl: '/42/pants.jpg' },
    { id: 11, name: 'jacket', imgUrl: '/42/jacket.jpg' },
    { id: 12, name: 'boots', imgUrl: '/42/boots.jpg' },
    { id: 13, name: 'cap', imgUrl: '/42/cap.jpg' },
    { id: 14, name: 'play tag', imgUrl: '/42/playtag.jpg' },
    { id: 15, name: 'play cards', imgUrl: '/42/playcards.jpg' },
    { id: 16, name: 'play dodgeball', imgUrl: '/42/playdodgeball.jpg' },
    { id: 17, name: 'make a snowman', imgUrl: '/42/makeasnowman.jpg' },
  ],
};

export default cardGenres;
